#!/bin/bash
disks_snaps(){
while read dataset; do
    snaps=$(zfs list -rHtsnap -o name -s creation $dataset)
    origin=$(zfs get -Hpo value origin $dataset)
    omix_sync=$(echo "$snaps" | sed -ne 's/^.*@omix_sync.@$/@omix_sync/')
    snap_first=$(echo "$snaps" | sed -ne '1 s/^.*@/@/p')
    [ $origin = - ] || snap_first=$origin
    [ -z $omix_sync ] || snap_first=$omix_sync
    echo $dataset $snap_first
done
}

config=`pct config $1 2>/dev/null`
bak_skip='/^mp[[:digit:]]\+:/{/.*backup=\(1\|yes\|on\|true\)/I!d}'
if [ -z "$config" ]; then
    config=`qm config $1 2>/dev/null`
    bak_skip='/backup=\(0\|no\|off\|false\)/Id'
fi
if [ -z "$config" ]; then
    (>&2 echo "error: unknown VMID: $1")
fi
#set -x
echo "$config" | sed "
/^\(\(\(virtio\|ide\|scsi\|sata\|mp\)[[:digit:]]\+\)\|rootfs\): .*$/b next
d
: next
/cdrom\|none/d
$bak_skip
s/^[^:]\+: /,/
s/file=\|volume=//
s/^.*,\([A-Za-z0-9]\+:\)\([/.A-Za-z0-9\-]\+\),\?.*$/\1\2/
s/\(.*\)/pvesm path \1 /
" | bash - | sed -ne's,^/\(dev/zvol/\)\?,zfs list -Ho name ,p' | bash - 2>/dev/null | disks_snaps
